project_name: monitoring-agent

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w
      - -X main.VERSION={{.Version}}
      - -X main.BUILDDATE={{.Date}}
      - -X main.GITCOMMIT={{.ShortCommit}}
nfpms:
  - license: AGPL-3.0
    maintainer: Dominik Robert <Dominik.Robert@Continentale.de>, Thorsten Eurich <Thorsten.Eurich@Continentale.de>
    homepage: https://github.com/continentale/monitoring-agent
    formats:
      - deb
    contents:
      - src: config.toml
        dst: /etc/monitoring-agent/config.toml
        type: config
      - src: packaging/deb/monitoring-agent.initd
        dst: /etc/init.d/monitoring-agent
        type: config
        packager: deb
      - src: packaging/deb/monitoring-agent.service
        dst: /etc/systemd/system/monitoring-agent.service
        type: config
        packager: deb
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'